services:
  android-emulator:
    image: budtmo2/docker-android-pro:emulator_16.0
    container_name: android-container
    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: "true"
    devices:
      - "/dev/kvm:/dev/kvm"
    ports:
      - "6080:6080"
    networks:
      - android-net
    restart: unless-stopped

  android-mcp:
    image: budtmo/docker-android:mcp
    environment:
      EMULATOR_HOST: android-emulator
      EMULATOR_PORT: 5555
    depends_on:
      - android-emulator
    networks:
      - android-net
    restart: unless-stopped

  agent:
    image: budtmo2/docker-android-pro:agent
    environment:
      MCP_SERVER_URL: http://android-mcp:8000/mcp
      # Leave it empty if it doesnt need any Bearer token
      MCP_TOKEN: ""
      # It could be http://local-llm:8000/v1 for vllm
      LLM_BASE_URL: http://local-llm:11434/v1
      # Leave it empty if it doesnt need any Bearer token
      LLM_API_KEY: ""
      # It could be Qwen/Qwen3.8:27B for vllm
      LLM_MODEL: qwen3.8:27b
    ports:
      - "8501:8501"
    depends_on:
      - android-mcp
    networks:
      - android-net
    extra_hosts:
      # Change with the ip where your local-llm is running (it could be ollama or vllm)
      - "local-llm:xx.xx.xx.xx"
    restart: unless-stopped

networks:
  android-net:
    driver: bridge
